kind: Template
apiVersion: v1
template: ghost-pathfinder
metadata:
  name: ghost-pathfinder
objects:

- kind: Service
  apiVersion: v1
  metadata:
    name: ${GHOST_PATHFINDER_NAME}
    labels:
      name: ${GHOST_PATHFINDER_NAME}
  spec:
    ports:
      - name: ghost-port
        protocol: TCP
        port: 1984
        targetPort: 1984
    selector:
      name: ${GHOST_PATHFINDER_NAME}

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${GHOST_PATHFINDER_NAME}
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ConfigChange
    replicas: 1
    selector:
      name: ${GHOST_PATHFINDER_NAME}
    template:
      metadata:
        labels:
          name: ${GHOST_PATHFINDER_NAME}
      spec:
        containers:
          - name: ${GHOST_PATHFINDER_NAME}
            image: ${GHOST_PATHFINDER_IMAGE}
            ports:
              - name: ghost-port
                containerPort: 1984
                protocol: TCP

parameters:
- name: GHOST_PATHFINDER_IMAGE
  description: Full name of the ghost pathfinder image
  value: docker.io/elmiko/ghost-pathfinder
- name: GHOST_PATHFINDER_NAME
  description: name for the ghost-pathfinder
  value: ghost-pathfinder
